all: romanNum magicDate areas bodyMassIndex timeCalculator changeGame

romanNum: romanNum.cpp
	g++ romanNum.cpp -o romanNum

magicDate: magicDate.cpp
	g++ magicDate.cpp -o magicDate

areas: areas.cpp
	g++ areas.cpp -o areas

bodyMassIndex: bodyMassIndex.cpp
	g++ bodyMassIndex.cpp -o bodyMassIndex

timeCalculator: timeCalculator.cpp
	g++ timeCalculator.cpp -o timeCalculator

changeGmae: changeGmae.cpp
	g++ changeGmae.cpp -o changeGmae